-- Create subscriptions table
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  email text not null,
  location text not null,
  type text not null default 'district',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(email, location, type)
);

-- Enable Row Level Security (RLS)
alter table public.subscriptions enable row level security;

-- Create policy to allow full access (for backend service role)
-- Note: In a real app, you'd want stricter policies. 
-- Since we use the service role key (or if using anon with just insert), verify access.
-- For simplicity in this demo, we can allow anon insert/select if needed, 
-- but ideally backend uses SERVICE_ROLE_KEY to bypass RLS.
